[package]
name = "betternotes"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "betternotes"
path = "src/main.rs"
test = false

[[test]]
name = "qml"
path = "tests/qml.rs"
harness = false

[dependencies]
betternotes-core = { path = "../crates/core" }
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true
serde_json.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true

[dev-dependencies]
tempfile.workspace = true
